apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka-cluster
data:
  CLUSTER_ID: "MkQwNDI4MTMwMTJhNDAxOQ"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "0@192.168.1.26:30093,1@192.168.1.26:30095,2@192.168.1.26:30097"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LOG_DIR: "/var/lib/kafka/data"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-0-config
  namespace: kafka-cluster
data:
  KAFKA_BROKER_ID: "0"
  KAFKA_NODE_ID: "0"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.26:30092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-1-config
  namespace: kafka-cluster
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_NODE_ID: "1"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.26:30094"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-2-config
  namespace: kafka-cluster
data:
  KAFKA_BROKER_ID: "2"
  KAFKA_NODE_ID: "2"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://192.168.1.26:30096"
