apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1
  namespace: kafka-cluster
spec:
  type: NodePort
  selector:
    broker: "1"
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30094
      name: kafka
    - port: 9093
      targetPort: 9093
      nodePort: 30095
      name: controller
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-kafka-broker-1-0
  namespace: kafka-cluster
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: kafka-data-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker-1
  namespace: kafka-cluster
spec:
  serviceName: kafka-broker-1
  replicas: 1
  selector:
    matchLabels:
      broker: "1"
  template:
    metadata:
      labels:
        broker: "1"
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9093
              name: controller
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          env:
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: CLUSTER_ID
            - name: KAFKA_BROKER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-1-config
                  key: KAFKA_BROKER_ID
            - name: KAFKA_NODE_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-1-config
                  key: KAFKA_NODE_ID
            - name: KAFKA_PROCESS_ROLES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_PROCESS_ROLES
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_INTER_BROKER_LISTENER_NAME
            - name: KAFKA_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LISTENERS
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-broker-1-config
                  key: KAFKA_ADVERTISED_LISTENERS
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CONTROLLER_LISTENER_NAMES
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CONTROLLER_QUORUM_VOTERS
            - name: KAFKA_LOG_DIR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_LOG_DIR
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_DEFAULT_REPLICATION_FACTOR
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            - name: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-kafka-broker-1-0
